apiVersion: v1
kind: ServiceAccount
metadata:
  name: ${BENCHMARK_RISINGWAVE_NAME}
  namespace: ${BENCHMARK_RISINGWAVE_NAMESPACE}
  annotations:
    eks.amazonaws.com/role-arn: ${BENCHMARK_RISINGWAVE_IAM_ROLE_ARN}
